name: ci

on:
  push:
    branches: [ "main", "master" ]

permissions:
  security-events: write
  contents: read

jobs:
  seguridad:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Bandit usando su acción oficial (esto evita errores de rutas)
      - name: Bandit Scan
        uses: shundor/python-bandit-scan@9ccf06f52e256860882e3409159981881477759d
        with:
          exit_code: 0 # Para que no rompa el pipeline si encuentra fallos

      # Semgrep usando su acción oficial
      - name: Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          generateSarif: "1"

      # Subir los resultados a la pestaña Security (GitHub los busca por defecto)
      - name: Upload Bandit SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: bandit.sarif

      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
