name: ci

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  security-events: write

jobs:
  bandit_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit Scan
        # Quitamos los filtros estrictos para asegurar que encuentre algo y cree los archivos
        run: |
          bandit -r . -f json -o sast-bandit.json || true
          bandit -r . -f sarif -o bandit-results.sarif || true
      - name: Upload Bandit Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandit-results
          path: sast-bandit.json
          if-no-files-found: warn
      - name: Upload Bandit SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: bandit-results.sarif

  semgrep_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          docker run --rm -v $(pwd):/src returntocorp/semgrep semgrep scan --severity=ERROR --severity=WARNING --json --output=sast-semgrep.json || true
          docker run --rm -v $(pwd):/src returntocorp/semgrep semgrep scan --severity=ERROR --severity=WARNING --sarif --output=semgrep-results.sarif || true
      - name: Upload Semgrep Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: sast-semgrep.json
          if-no-files-found: warn
      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: semgrep-results.sarif

  build_and_scout:
    needs: [bandit_scan, semgrep_scan]
    runs-on: ubuntu-latest
    if: always() # Para que se ejecute aunque los anteriores tengan avisos
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t pygoat:latest .
      - name: Docker Scout Scan
        uses: docker/scout-action@v1
        with:
          command: quickview, cves
          image: pygoat:latest
